# Generated by Django 4.2 on 2024-08-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZellularTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pull', 'Pull'), ('push', 'Push')], max_length=4)),
                ('method', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
