# Generated by Django 4.0.4 on 2024-08-03 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symbol', '0002_chain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4)),
                ('amount', models.BigIntegerField()),
                ('filled_amount', models.BigIntegerField(default=0)),
                ('price', models.BigIntegerField()),
                ('time', models.DateTimeField()),
                ('nonce', models.BigIntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbol.symbol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
