# Generated by Django 4.2 on 2024-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbol', '0002_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='signature',
            field=models.JSONField(null=True),
        ),
    ]
